snap: 50
metrics:
- fid50k_full
random_seed: 0
resolution: 256
gpus: 1
cond: false
train_dataset:
  dataset:
    name: ImageFolderDataset
    args:
      path: /home/song/codes/datasets/images256x256.zip
      use_labels: false
      max_size: null
      xflip: false
      resolution: 256
  wrapper:
    name: no-wrapper
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16
  num_workers: 1
cfg: auto
gamma: 0.8192
ema_kimg: 5.0
ema_rampup: 0.05
kimg: 25000
aug: ada
p: none
target: none
augpipe: bgc
resume: noresume
fp32: false
nhwc: false
cudnn_benchmark: true
allow_tf32: false
model-G:
  name: style-generator
  args:
    z_dim: 512
    w_dim: 512
    c_dim: 0
    img_resolution: 256
    img_channels: 3
    mapping_kwargs:
      num_layers: 2
    synthesis_kwargs:
      channel_base: 32768
      channel_max: 512
      num_fp16_res: 4
      conv_clamp: 256
model-D:
  name: style-discriminator
  args:
    c_dim: 0
    img_resolution: 256
    img_channels: 3
    channel_base: 32768
    channel_max: 512
    num_fp16_res: 4
    conv_clamp: 256
    block_kwargs:
      freeze_layers: 0
    mapping_kwargs: null
    epilogue_kwargs:
      mbstd_group_size: 4
model-Aug:
  name: style-augment
  args:
    xflip: 1
    rotate90: 1
    xint: 1
    scale: 1
    rotate: 1
    aniso: 1
    xfrac: 1
    brightness: 1
    contrast: 1
    lumaflip: 1
    hue: 1
    saturation: 1
optimizer-G:
  name: adam
  args:
    lr: 0.0002
    betas:
    - 0
    - 0.99
    eps: 1.0e-08
optimizer-D:
  name: adam
  args:
    lr: 0.0002
    betas:
    - 0
    - 0.99
    eps: 1.0e-08
G_reg_interval: 4
D_reg_interval: 16
image_snapshot_ticks: 50
network_snapshot_ticks: 50
ada_target: 0.6
augment_p: 0
resume_pkl: null
