### yaml file is recognized as dict include int/str/bool/float/list-int/list-str
### none or None is recognized as str, not None


## 1. General
# snap: snapshot to save model. unit: ticks. [int]
snap: 50
# metrics: evaluate the GAN model. [str list]
metrics: ['fid50k_full']
# random_seed: reproduction for the model. [int]
random_seed: 0
# resolution: resolution of images. [int]
resolution: 256
# gpus: num of gpus. [int]
gpus: 1

## 2. Dataset
# cond: training data condition. [bool]
cond: false
# training dataset
train_dataset:
  dataset:
    name: ImageFolderDataset
    args:
      path: /home/song/codes/datasets/images256x256.zip
  wrapper:
    name: no-wrapper
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16
  num_workers: 1

## 3. base config
# cfg: base config of styleGAN. str [auto,stylegan2,paper256,paper512,paper1024,cifar]
cfg: auto # not use in code
# gamma: override R1 gamma, use for loss. [float]
gamma: none
# ema_kimg: ref ema of ensure_config.py line 17
ema_kimg: none
# ema_rampup:
ema_rampup: 0.05
# kimg: training duration. [int]
kimg: none

## 4. discriminator augmentation
# aug: augment mode. str [ada,noaug,fixed]
aug: fixed
# p: augmentation probability for aug=fixed. [float]
p: 0
# target: ada target value for aug=ada. [float]
target: none
# augpipe: augment pipeline. str [blit,geom,color,filter,noise,cutout,bg,bgc,bgcf,bgcfn,bgcfnc]
augpipe: bgc
ada_kimg: 1000

## 5. transfer learning
# resume: resume training. str path
resume: null

## 6. performance options
# fp32: disable mixed-precision training. [bool]
fp32: false
# nhwc: use NHWC memory format with FP16. [bool]
nhwc: false
# cudnn_benchmark: disable cuDNN benchmarking. [bool]
cudnn_benchmark: true
# allow-tf32: allow pytorch to use TF32 internally. [bool]
allow_tf32: false

model-G:
  name: style-generator
  args:
    z_dim: 512
    w_dim: 512
    c_dim: 0
    img_resolution: 256
    img_channels: 3
    mapping_kwargs:
      num_layers: 2 # or 8
    synthesis_kwargs:
      channel_base: 32768
      channel_max: 512
      num_fp16_res: 4
      conv_clamp: 256

model-D:
  name: style-discriminator
  args:
    c_dim: 0
    img_resolution: 256
    img_channels: 3
    channel_base: 32768
    channel_max: 512
    num_fp16_res: 4
    conv_clamp: 256
    block_kwargs:
      freeze_layers: 0
    mapping_kwargs:
    epilogue_kwargs:
      mbstd_group_size: 4

model-Aug:
  name: style-augment
  args: null # wait for init


optimizer-G:
  name: adam
  args:
    lr: 0.0002
    betas: [0,0.99]
    eps: 1.e-8

optimizer-D:
  name: adam
  args:
    lr: 0.0002
    betas: [0,0.99]
    eps: 1.e-8

G_reg_interval: 4
D_reg_interval: 16